import subprocess
import os
import re
from datetime import datetime
import sys

def github_to_deepwiki(github_url):
    """
    Convert GitHub URL to DeepWiki URL
    Example: https://github.com/openai/openai-python -> https://deepwiki.com/openai/openai-python
    """
    # Extract owner and repo from GitHub URL
    pattern = r'github\.com/([^/]+)/([^/]+)'
    match = re.search(pattern, github_url)

    if not match:
        raise ValueError("Invalid GitHub URL format")

    owner = match.group(1)
    repo = match.group(2).replace('.git', '')

    deepwiki_url = f"https://deepwiki.com/{owner}/{repo}"
    return deepwiki_url

def run_deepwiki_scraper(deepwiki_url, output_dir):
    """
    Run the deepwiki_to_md scraper using the package from Desktop
    Returns the output directory where markdown files are saved
    """
    try:
        # Path to the deepwiki_to_md package (in Docker container or local)
        backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        deepwiki_path = os.path.join(backend_dir, 'deepwiki_to_md')

        # Fallback to absolute path if relative doesn't exist
        if not os.path.exists(deepwiki_path):
            deepwiki_path = '/app/deepwiki_to_md'

        # Get absolute path for output directory
        abs_output_dir = os.path.join(backend_dir, output_dir)

        # Run the scraper using Python module
        cmd = [
            sys.executable, '-m', 'deepwiki_to_md.run_scraper',
            deepwiki_url,
            '--output-dir', abs_output_dir
        ]

        print(f"Running command: {' '.join(cmd)}")
        print(f"Working directory: {deepwiki_path}")
        print(f"Output directory: {abs_output_dir}")

        # Run the scraper
        result = subprocess.run(
            cmd,
            cwd=deepwiki_path,
            capture_output=True,
            text=True,
            timeout=120  # 2 minute timeout
        )

        print(f"Return code: {result.returncode}")
        print(f"STDOUT: {result.stdout}")
        print(f"STDERR: {result.stderr}")

        if result.returncode == 0:
            print(f"Scraper completed successfully")
            return True
        else:
            print(f"Scraper failed with return code {result.returncode}")
            return False

    except subprocess.TimeoutExpired:
        print("Scraper timed out after 2 minutes")
        return False
    except Exception as e:
        print(f"Error running scraper: {str(e)}")
        import traceback
        traceback.print_exc()
        return False

def generate_mock_documentation(deepwiki_url):
    """
    Generate mock documentation for testing when deepwiki is unavailable
    """
    repo_name = deepwiki_url.split('/')[-1]
    owner = deepwiki_url.split('/')[-2]

    markdown = f"""# {repo_name}

Repository documentation generated from DeepWiki.

**Owner:** {owner}
**Repository:** {repo_name}
**Source:** {deepwiki_url}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Overview

This is auto-generated documentation for the {repo_name} repository.

## Installation

```bash
pip install {repo_name}
```

## Quick Start

```python
import {repo_name}

# Your code here
```

## Features

- Feature 1: Core functionality
- Feature 2: Advanced features
- Feature 3: Integration capabilities

## Documentation

For full documentation, visit: {deepwiki_url}

## API Reference

### Main Classes

#### Class: MainClass

Primary class for {repo_name} functionality.

**Methods:**
- `method1()` - Description of method 1
- `method2()` - Description of method 2

### Utility Functions

- `helper_function()` - Utility helper function
- `process_data()` - Data processing function

## Examples

```python
# Example 1: Basic usage
from {repo_name} import MainClass

obj = MainClass()
result = obj.method1()
```

```python
# Example 2: Advanced usage
from {repo_name} import helper_function

data = helper_function()
processed = process_data(data)
```

## Configuration

Configuration options for {repo_name}:

- `option1`: Description
- `option2`: Description
- `option3`: Description

## Contributing

Contributions are welcome! Please see the contributing guidelines.

## License

This project is licensed under the MIT License.

---

*Documentation generated by NYC Code*
"""
    return markdown

def generate_documentation(github_url):
    """
    Main function to generate documentation from GitHub URL
    """
    try:
        # Step 1: Convert GitHub URL to DeepWiki URL
        deepwiki_url = github_to_deepwiki(github_url)
        print(f"Converted to DeepWiki URL: {deepwiki_url}")

        # Extract repo info for folder structure
        pattern = r'github\.com/([^/]+)/([^/]+)'
        match = re.search(pattern, github_url)
        owner = match.group(1)
        repo = match.group(2).replace('.git', '')

        # Create output directory: output/{owner}_{repo}
        repo_folder = f"{owner}_{repo}"
        output_dir = os.path.join('output', repo_folder)
        os.makedirs(output_dir, exist_ok=True)

        # Step 2: Run deepwiki_to_md scraper
        success = run_deepwiki_scraper(deepwiki_url, output_dir)

        if success:
            # The scraper creates files in: output/{repo_folder}/{repo}/md/*.md
            # We need to look for the md folder
            md_folder = None
            for root, dirs, files in os.walk(output_dir):
                if 'md' in dirs:
                    md_folder = os.path.join(root, 'md')
                    break

            if not md_folder:
                # Try direct path
                md_folder = os.path.join(output_dir, repo, 'md')

            print(f"Looking for markdown files in: {md_folder}")

            # Read all generated markdown files
            markdown_files = []
            if os.path.exists(md_folder):
                for file in os.listdir(md_folder):
                    if file.endswith('.md'):
                        filepath = os.path.join(md_folder, file)
                        with open(filepath, 'r', encoding='utf-8') as f:
                            content = f.read()
                            markdown_files.append({
                                'filename': file,
                                'content': content
                            })
            else:
                print(f"Warning: md folder not found at {md_folder}")

            # Combine all markdown for preview
            combined_markdown = f"# Documentation for {repo}\n\n"
            combined_markdown += f"**Generated from:** {deepwiki_url}\n\n"
            combined_markdown += f"**Total files:** {len(markdown_files)}\n\n"
            for md_file in markdown_files:
                combined_markdown += f"\n---\n## {md_file['filename']}\n\n{md_file['content']}\n\n"

            print(f"Generated {len(markdown_files)} markdown files")

            return {
                'markdown': combined_markdown,
                'markdown_files': markdown_files,
                'deepwiki_url': deepwiki_url,
                'github_url': github_url,
                'repo_folder': repo_folder,
                'md_folder_path': md_folder
            }
        else:
            raise Exception("Scraper failed to generate documentation")

    except Exception as e:
        raise Exception(f"Documentation generation failed: {str(e)}")
